name    'kireevco-luasense'
version '0.1.0'
source 'UNKNOWN'
author 'kireevco'
license 'MIT'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/rabbitmq', '>= 5.1.0'
